Predicción 1:
Function myBirthYearFunc(){
    console.log("Nací en " + 1980);

}      -> // "Nací en 1980"

Predicción 2:
function myBirthYearFunc(EntradaAñoNacimiento){
    console.log("Nací en " + EntradaAñoNacimiento);

}      -> // "Nací en 1980"

Predicción 3:
function add(num1, num2){
    console.log("¡Sumando números!");
    console.log("num1 is: " + 10);
    console.log("num2 is: " + 20);
    var sum = num1 + num2;
    console.log(sum);

}     -> // console.log(sum) = 30